import org.ktu.examples.BasicCalculator;
import org.junit.rules.ExpectedException;
import org.junit.Rule;
public class TestBasicCalculatorFields
{
@Rule
 public final ExpectedException exception = ExpectedException.none();
/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void BasicCalculatorFields1() throws Throwable
	{
		BasicCalculator testObject = new BasicCalculator();
		testObject.setMagicNumber((int)-10);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  inv: self.magicNumber = 42 " is satisfied. 
*/	@org.junit.Test
	public void BasicCalculatorFields2() throws Throwable
	{
		BasicCalculator testObject = new BasicCalculator();
		exception.expect(Throwable.class);
		testObject.setMagicNumber((int)43);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void BasicCalculatorFields3() throws Throwable
	{
		BasicCalculator testObject = new BasicCalculator();
		testObject.setMagicNumber((int)4);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  inv: self.magicNumber = 42 " is satisfied. 
*/	@org.junit.Test
	public void BasicCalculatorFields4() throws Throwable
	{
		BasicCalculator testObject = new BasicCalculator();
		testObject.setMagicNumber((int)42);
		org.junit.Assert.assertEquals(42, testObject.getMagicNumber());
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void BasicCalculatorFields5() throws Throwable
	{
		BasicCalculator testObject = new BasicCalculator();
		testObject.setMagicNumber((int)0);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  inv: self.magicNumber = 42 " is satisfied. 
*/	@org.junit.Test
	public void BasicCalculatorFields6() throws Throwable
	{
		BasicCalculator testObject = new BasicCalculator();
		exception.expect(Throwable.class);
		testObject.setMagicNumber((int)41);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void BasicCalculatorFields7() throws Throwable
	{
		BasicCalculator testObject = new BasicCalculator();
		testObject.setMagicNumber((int)0);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  inv: self.magicNumber = 42 " is satisfied. 
*/	@org.junit.Test
	public void BasicCalculatorFields8() throws Throwable
	{
		BasicCalculator testObject = new BasicCalculator();
		testObject.setMagicNumber((int)42);
		org.junit.Assert.assertEquals(42, testObject.getMagicNumber());
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void BasicCalculatorFields9() throws Throwable
	{
		BasicCalculator testObject = new BasicCalculator();
		testObject.setMagicNumber((int)-2);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  inv: self.magicNumber = 42 " is satisfied. 
*/	@org.junit.Test
	public void BasicCalculatorFields10() throws Throwable
	{
		BasicCalculator testObject = new BasicCalculator();
		exception.expect(Throwable.class);
		testObject.setMagicNumber((int)43);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void BasicCalculatorFields11() throws Throwable
	{
		BasicCalculator testObject = new BasicCalculator();
		testObject.setMagicNumber((int)9);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  inv: self.magicNumber = 42 " is satisfied. 
*/	@org.junit.Test
	public void BasicCalculatorFields12() throws Throwable
	{
		BasicCalculator testObject = new BasicCalculator();
		testObject.setMagicNumber((int)42);
		org.junit.Assert.assertEquals(42, testObject.getMagicNumber());
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void BasicCalculatorFields13() throws Throwable
	{
		BasicCalculator testObject = new BasicCalculator();
		testObject.setMagicNumber((int)-8);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  inv: self.magicNumber = 42 " is satisfied. 
*/	@org.junit.Test
	public void BasicCalculatorFields14() throws Throwable
	{
		BasicCalculator testObject = new BasicCalculator();
		exception.expect(Throwable.class);
		testObject.setMagicNumber((int)43);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void BasicCalculatorFields15() throws Throwable
	{
		BasicCalculator testObject = new BasicCalculator();
		testObject.setMagicNumber((int)-10);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  inv: self.magicNumber = 42 " is satisfied. 
*/	@org.junit.Test
	public void BasicCalculatorFields16() throws Throwable
	{
		BasicCalculator testObject = new BasicCalculator();
		testObject.setMagicNumber((int)42);
		org.junit.Assert.assertEquals(42, testObject.getMagicNumber());
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void BasicCalculatorFields17() throws Throwable
	{
		BasicCalculator testObject = new BasicCalculator();
		testObject.setMagicNumber((int)-2);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  inv: self.magicNumber = 42 " is satisfied. 
*/	@org.junit.Test
	public void BasicCalculatorFields18() throws Throwable
	{
		BasicCalculator testObject = new BasicCalculator();
		exception.expect(Throwable.class);
		testObject.setMagicNumber((int)41);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void BasicCalculatorFields19() throws Throwable
	{
		BasicCalculator testObject = new BasicCalculator();
		testObject.setMagicNumber((int)3);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  inv: self.magicNumber = 42 " is satisfied. 
*/	@org.junit.Test
	public void BasicCalculatorFields20() throws Throwable
	{
		BasicCalculator testObject = new BasicCalculator();
		testObject.setMagicNumber((int)42);
		org.junit.Assert.assertEquals(42, testObject.getMagicNumber());
	};

};
