import org.ktu.examples.SimulatedAnnealing;
import org.junit.rules.ExpectedException;
import org.junit.Rule;
public class TestgetWrongChoiceProb
{
@Rule
 public final ExpectedException exception = ExpectedException.none();
/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testGetWrongChoiceProb1() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();

		double res = testObject.getWrongChoiceProb(-8.86, 188.62);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testGetWrongChoiceProb2() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();

		double res = testObject.getWrongChoiceProb(217.55, -414.74);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testGetWrongChoiceProb3() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();

		double res = testObject.getWrongChoiceProb(25.17, 27.18);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testGetWrongChoiceProb4() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();

		double res = testObject.getWrongChoiceProb(-241.52, -163.28);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testGetWrongChoiceProb5() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();

		double res = testObject.getWrongChoiceProb(-19.90, -85.36);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testGetWrongChoiceProb6() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();

		double res = testObject.getWrongChoiceProb(1.78, -259.88);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testGetWrongChoiceProb7() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();

		double res = testObject.getWrongChoiceProb(111.64, -251.27);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testGetWrongChoiceProb8() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();

		double res = testObject.getWrongChoiceProb(-365.55, 263.62);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testGetWrongChoiceProb9() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();

		double res = testObject.getWrongChoiceProb(-325.61, -35.17);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testGetWrongChoiceProb10() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();

		double res = testObject.getWrongChoiceProb(302.76, -176.62);
	};

};
