import org.ktu.examples.GeometryCalculator;
import org.junit.rules.ExpectedException;
import org.junit.Rule;
public class TestperimeterOfSquare
{
@Rule
 public final ExpectedException exception = ExpectedException.none();
/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testPerimeterOfSquare1() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.perimeterOfSquare(-109.73);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: a > 0 " is satisfied. 
*/	@org.junit.Test
	public void testPerimeterOfSquare2() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = 0;
		exception.expect(Throwable.class);

		double res = testObject.perimeterOfSquare(mca_a);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 4*a " is satisfied. 
*/	@org.junit.Test
	public void testPerimeterOfSquare3() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = 23.033304776077742;

		double res = testObject.perimeterOfSquare(mca_a);
		org.junit.Assert.assertEquals(92.13321910431097, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: a > 0 " is satisfied. 
*/	@org.junit.Test
	public void testPerimeterOfSquare4() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = 0;
		exception.expect(Throwable.class);

		double res = testObject.perimeterOfSquare(mca_a);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testPerimeterOfSquare5() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.perimeterOfSquare(173.30);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: a > 0 " is satisfied. 
*/	@org.junit.Test
	public void testPerimeterOfSquare6() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = 0;
		exception.expect(Throwable.class);

		double res = testObject.perimeterOfSquare(mca_a);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 4*a " is satisfied. 
*/	@org.junit.Test
	public void testPerimeterOfSquare7() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = -340.48871752721493;

		double res = testObject.perimeterOfSquare(mca_a);
		org.junit.Assert.assertEquals(-1361.9548701088597, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: a > 0 " is satisfied. 
*/	@org.junit.Test
	public void testPerimeterOfSquare8() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = 0;
		exception.expect(Throwable.class);

		double res = testObject.perimeterOfSquare(mca_a);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testPerimeterOfSquare9() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.perimeterOfSquare(-16.40);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: a > 0 " is satisfied. 
*/	@org.junit.Test
	public void testPerimeterOfSquare10() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = 0;
		exception.expect(Throwable.class);

		double res = testObject.perimeterOfSquare(mca_a);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 4*a " is satisfied. 
*/	@org.junit.Test
	public void testPerimeterOfSquare11() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = -125.14466461165901;

		double res = testObject.perimeterOfSquare(mca_a);
		org.junit.Assert.assertEquals(-500.57865844663604, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: a > 0 " is satisfied. 
*/	@org.junit.Test
	public void testPerimeterOfSquare12() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = -1;
		exception.expect(Throwable.class);

		double res = testObject.perimeterOfSquare(mca_a);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testPerimeterOfSquare13() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.perimeterOfSquare(-354.79);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: a > 0 " is satisfied. 
*/	@org.junit.Test
	public void testPerimeterOfSquare14() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = -1;
		exception.expect(Throwable.class);

		double res = testObject.perimeterOfSquare(mca_a);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 4*a " is satisfied. 
*/	@org.junit.Test
	public void testPerimeterOfSquare15() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = 8.94113019102025;

		double res = testObject.perimeterOfSquare(mca_a);
		org.junit.Assert.assertEquals(35.764520764081, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: a > 0 " is satisfied. 
*/	@org.junit.Test
	public void testPerimeterOfSquare16() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = 0;
		exception.expect(Throwable.class);

		double res = testObject.perimeterOfSquare(mca_a);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testPerimeterOfSquare17() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.perimeterOfSquare(-343.21);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: a > 0 " is satisfied. 
*/	@org.junit.Test
	public void testPerimeterOfSquare18() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = 0;
		exception.expect(Throwable.class);

		double res = testObject.perimeterOfSquare(mca_a);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 4*a " is satisfied. 
*/	@org.junit.Test
	public void testPerimeterOfSquare19() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = 203.72481483970626;

		double res = testObject.perimeterOfSquare(mca_a);
		org.junit.Assert.assertEquals(814.899259358825, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: a > 0 " is satisfied. 
*/	@org.junit.Test
	public void testPerimeterOfSquare20() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = 0;
		exception.expect(Throwable.class);

		double res = testObject.perimeterOfSquare(mca_a);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testPerimeterOfSquare21() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.perimeterOfSquare(-216.06);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: a > 0 " is satisfied. 
*/	@org.junit.Test
	public void testPerimeterOfSquare22() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = 0;
		exception.expect(Throwable.class);

		double res = testObject.perimeterOfSquare(mca_a);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 4*a " is satisfied. 
*/	@org.junit.Test
	public void testPerimeterOfSquare23() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = -121.20889328253838;

		double res = testObject.perimeterOfSquare(mca_a);
		org.junit.Assert.assertEquals(-484.83557313015353, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: a > 0 " is satisfied. 
*/	@org.junit.Test
	public void testPerimeterOfSquare24() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = 0;
		exception.expect(Throwable.class);

		double res = testObject.perimeterOfSquare(mca_a);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testPerimeterOfSquare25() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.perimeterOfSquare(226.11);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: a > 0 " is satisfied. 
*/	@org.junit.Test
	public void testPerimeterOfSquare26() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = 0;
		exception.expect(Throwable.class);

		double res = testObject.perimeterOfSquare(mca_a);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 4*a " is satisfied. 
*/	@org.junit.Test
	public void testPerimeterOfSquare27() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = -142.04723373738733;

		double res = testObject.perimeterOfSquare(mca_a);
		org.junit.Assert.assertEquals(-568.1889349495493, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: a > 0 " is satisfied. 
*/	@org.junit.Test
	public void testPerimeterOfSquare28() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = 0;
		exception.expect(Throwable.class);

		double res = testObject.perimeterOfSquare(mca_a);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testPerimeterOfSquare29() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.perimeterOfSquare(-128.94);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: a > 0 " is satisfied. 
*/	@org.junit.Test
	public void testPerimeterOfSquare30() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = 0;
		exception.expect(Throwable.class);

		double res = testObject.perimeterOfSquare(mca_a);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 4*a " is satisfied. 
*/	@org.junit.Test
	public void testPerimeterOfSquare31() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = 87.8064912411615;

		double res = testObject.perimeterOfSquare(mca_a);
		org.junit.Assert.assertEquals(351.225964964646, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: a > 0 " is satisfied. 
*/	@org.junit.Test
	public void testPerimeterOfSquare32() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = 0;
		exception.expect(Throwable.class);

		double res = testObject.perimeterOfSquare(mca_a);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testPerimeterOfSquare33() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.perimeterOfSquare(94.35);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: a > 0 " is satisfied. 
*/	@org.junit.Test
	public void testPerimeterOfSquare34() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = 0;
		exception.expect(Throwable.class);

		double res = testObject.perimeterOfSquare(mca_a);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 4*a " is satisfied. 
*/	@org.junit.Test
	public void testPerimeterOfSquare35() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = -157.9063201988464;

		double res = testObject.perimeterOfSquare(mca_a);
		org.junit.Assert.assertEquals(-631.6252807953856, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: a > 0 " is satisfied. 
*/	@org.junit.Test
	public void testPerimeterOfSquare36() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = 0;
		exception.expect(Throwable.class);

		double res = testObject.perimeterOfSquare(mca_a);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testPerimeterOfSquare37() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.perimeterOfSquare(-310.63);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: a > 0 " is satisfied. 
*/	@org.junit.Test
	public void testPerimeterOfSquare38() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = 0;
		exception.expect(Throwable.class);

		double res = testObject.perimeterOfSquare(mca_a);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 4*a " is satisfied. 
*/	@org.junit.Test
	public void testPerimeterOfSquare39() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = 227.6749002231988;

		double res = testObject.perimeterOfSquare(mca_a);
		org.junit.Assert.assertEquals(910.6996008927952, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: a > 0 " is satisfied. 
*/	@org.junit.Test
	public void testPerimeterOfSquare40() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = 0;
		exception.expect(Throwable.class);

		double res = testObject.perimeterOfSquare(mca_a);
	};

};
