import org.ktu.examples.SimulatedAnnealing;
import org.junit.rules.ExpectedException;
import org.junit.Rule;
public class TestfitnessFunction
{
@Rule
 public final ExpectedException exception = ExpectedException.none();
/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testFitnessFunction1() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();

		double res = testObject.fitnessFunction(-218.95);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 50-self.bestValue+valueToCheck " is satisfied. 
*/	@org.junit.Test
	public void testFitnessFunction2() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_valueToCheck = -350.684176760788;

		double res = testObject.fitnessFunction(mca_valueToCheck);
		org.junit.Assert.assertEquals(-471.46223407729013, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 50-self.bestValue+valueToCheck " is satisfied. 
*/	@org.junit.Test
	public void testFitnessFunction3() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_valueToCheck = -237.91055299521778;

		double res = testObject.fitnessFunction(mca_valueToCheck);
		org.junit.Assert.assertEquals(-43.37287776511906, res, 0.001);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testFitnessFunction4() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();

		double res = testObject.fitnessFunction(-223.21);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 50-self.bestValue+valueToCheck " is satisfied. 
*/	@org.junit.Test
	public void testFitnessFunction5() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_valueToCheck = -298.6039580335108;

		double res = testObject.fitnessFunction(mca_valueToCheck);
		org.junit.Assert.assertEquals(257.20447480824294, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 50-self.bestValue+valueToCheck " is satisfied. 
*/	@org.junit.Test
	public void testFitnessFunction6() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_valueToCheck = -7.5301287874278415;

		double res = testObject.fitnessFunction(mca_valueToCheck);
		org.junit.Assert.assertEquals(521.2093046696016, res, 0.001);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testFitnessFunction7() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();

		double res = testObject.fitnessFunction(-370.38);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 50-self.bestValue+valueToCheck " is satisfied. 
*/	@org.junit.Test
	public void testFitnessFunction8() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_valueToCheck = -292.7005271934994;

		double res = testObject.fitnessFunction(mca_valueToCheck);
		org.junit.Assert.assertEquals(361.44103282762546, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 50-self.bestValue+valueToCheck " is satisfied. 
*/	@org.junit.Test
	public void testFitnessFunction9() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_valueToCheck = -89.14152390059263;

		double res = testObject.fitnessFunction(mca_valueToCheck);
		org.junit.Assert.assertEquals(422.0804654670499, res, 0.001);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testFitnessFunction10() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();

		double res = testObject.fitnessFunction(-53.73);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 50-self.bestValue+valueToCheck " is satisfied. 
*/	@org.junit.Test
	public void testFitnessFunction11() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_valueToCheck = -259.54151382186456;

		double res = testObject.fitnessFunction(mca_valueToCheck);
		org.junit.Assert.assertEquals(335.29941220220417, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 50-self.bestValue+valueToCheck " is satisfied. 
*/	@org.junit.Test
	public void testFitnessFunction12() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_valueToCheck = 126.80961464951298;

		double res = testObject.fitnessFunction(mca_valueToCheck);
		org.junit.Assert.assertEquals(447.62884898683114, res, 0.001);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testFitnessFunction13() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();

		double res = testObject.fitnessFunction(78.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 50-self.bestValue+valueToCheck " is satisfied. 
*/	@org.junit.Test
	public void testFitnessFunction14() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_valueToCheck = -46.15467598264318;

		double res = testObject.fitnessFunction(mca_valueToCheck);
		org.junit.Assert.assertEquals(332.176037185797, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 50-self.bestValue+valueToCheck " is satisfied. 
*/	@org.junit.Test
	public void testFitnessFunction15() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_valueToCheck = -273.5600115662221;

		double res = testObject.fitnessFunction(mca_valueToCheck);
		org.junit.Assert.assertEquals(258.10768906419435, res, 0.001);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testFitnessFunction16() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();

		double res = testObject.fitnessFunction(0.38);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 50-self.bestValue+valueToCheck " is satisfied. 
*/	@org.junit.Test
	public void testFitnessFunction17() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_valueToCheck = 182.42344119983812;

		double res = testObject.fitnessFunction(mca_valueToCheck);
		org.junit.Assert.assertEquals(599.6672194340765, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 50-self.bestValue+valueToCheck " is satisfied. 
*/	@org.junit.Test
	public void testFitnessFunction18() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_valueToCheck = -401.87534564805446;

		double res = testObject.fitnessFunction(mca_valueToCheck);
		org.junit.Assert.assertEquals(-140.2051673174784, res, 0.001);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testFitnessFunction19() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();

		double res = testObject.fitnessFunction(0.59);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 50-self.bestValue+valueToCheck " is satisfied. 
*/	@org.junit.Test
	public void testFitnessFunction20() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_valueToCheck = 173.15180047826908;

		double res = testObject.fitnessFunction(mca_valueToCheck);
		org.junit.Assert.assertEquals(272.08513099194647, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 50-self.bestValue+valueToCheck " is satisfied. 
*/	@org.junit.Test
	public void testFitnessFunction21() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_valueToCheck = 404.1044444596467;

		double res = testObject.fitnessFunction(mca_valueToCheck);
		org.junit.Assert.assertEquals(570.2388272326817, res, 0.001);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testFitnessFunction22() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();

		double res = testObject.fitnessFunction(-212.65);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 50-self.bestValue+valueToCheck " is satisfied. 
*/	@org.junit.Test
	public void testFitnessFunction23() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_valueToCheck = -396.59629343008805;

		double res = testObject.fitnessFunction(mca_valueToCheck);
		org.junit.Assert.assertEquals(-487.5090005304306, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 50-self.bestValue+valueToCheck " is satisfied. 
*/	@org.junit.Test
	public void testFitnessFunction24() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_valueToCheck = -267.2792667629336;

		double res = testObject.fitnessFunction(mca_valueToCheck);
		org.junit.Assert.assertEquals(75.25013078322951, res, 0.001);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testFitnessFunction25() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();

		double res = testObject.fitnessFunction(-271.63);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 50-self.bestValue+valueToCheck " is satisfied. 
*/	@org.junit.Test
	public void testFitnessFunction26() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_valueToCheck = -209.108055435672;

		double res = testObject.fitnessFunction(mca_valueToCheck);
		org.junit.Assert.assertEquals(165.76785838993703, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 50-self.bestValue+valueToCheck " is satisfied. 
*/	@org.junit.Test
	public void testFitnessFunction27() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_valueToCheck = -90.67607857338444;

		double res = testObject.fitnessFunction(mca_valueToCheck);
		org.junit.Assert.assertEquals(71.67575738048637, res, 0.001);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testFitnessFunction28() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();

		double res = testObject.fitnessFunction(-92.80);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 50-self.bestValue+valueToCheck " is satisfied. 
*/	@org.junit.Test
	public void testFitnessFunction29() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_valueToCheck = -28.64422501920265;

		double res = testObject.fitnessFunction(mca_valueToCheck);
		org.junit.Assert.assertEquals(22.803086584968, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 50-self.bestValue+valueToCheck " is satisfied. 
*/	@org.junit.Test
	public void testFitnessFunction30() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_valueToCheck = -36.24847361247365;

		double res = testObject.fitnessFunction(mca_valueToCheck);
		org.junit.Assert.assertEquals(-53.663461965199424, res, 0.001);
	};

};
