import org.ktu.examples.GeometryCalculator;
import org.junit.rules.ExpectedException;
import org.junit.Rule;
public class TestsurfaceAreaOfSphere
{
@Rule
 public final ExpectedException exception = ExpectedException.none();
/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSphere1() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.surfaceAreaOfSphere(171.50);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: radius > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSphere2() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_radius = 0;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSphere(mca_radius);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 12.56637061*radius*radius " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSphere3() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_radius = 208.26618010271318;

		double res = testObject.surfaceAreaOfSphere(mca_radius);
		org.junit.Assert.assertEquals(545063.8511507774, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: radius > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSphere4() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_radius = -1;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSphere(mca_radius);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSphere5() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.surfaceAreaOfSphere(106.13);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: radius > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSphere6() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_radius = 0;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSphere(mca_radius);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 12.56637061*radius*radius " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSphere7() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_radius = -326.07540001583334;

		double res = testObject.surfaceAreaOfSphere(mca_radius);
		org.junit.Assert.assertEquals(1336121.4888190436, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: radius > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSphere8() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_radius = 0;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSphere(mca_radius);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSphere9() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.surfaceAreaOfSphere(8.24);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: radius > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSphere10() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_radius = -1;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSphere(mca_radius);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 12.56637061*radius*radius " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSphere11() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_radius = -107.69134350210949;

		double res = testObject.surfaceAreaOfSphere(mca_radius);
		org.junit.Assert.assertEquals(145737.55104167346, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: radius > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSphere12() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_radius = -1;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSphere(mca_radius);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSphere13() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.surfaceAreaOfSphere(168.92);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: radius > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSphere14() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_radius = -1;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSphere(mca_radius);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 12.56637061*radius*radius " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSphere15() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_radius = 99.71083633888804;

		double res = testObject.surfaceAreaOfSphere(mca_radius);
		org.junit.Assert.assertEquals(124938.01317588863, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: radius > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSphere16() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_radius = -1;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSphere(mca_radius);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSphere17() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.surfaceAreaOfSphere(-290.40);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: radius > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSphere18() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_radius = -1;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSphere(mca_radius);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 12.56637061*radius*radius " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSphere19() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_radius = -296.1138750024045;

		double res = testObject.surfaceAreaOfSphere(mca_radius);
		org.junit.Assert.assertEquals(1101862.4738431007, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: radius > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSphere20() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_radius = -1;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSphere(mca_radius);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSphere21() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.surfaceAreaOfSphere(-244.82);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: radius > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSphere22() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_radius = -1;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSphere(mca_radius);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 12.56637061*radius*radius " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSphere23() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_radius = -0.6659519829927234;

		double res = testObject.surfaceAreaOfSphere(mca_radius);
		org.junit.Assert.assertEquals(5.57308555607848, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: radius > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSphere24() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_radius = -1;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSphere(mca_radius);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSphere25() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.surfaceAreaOfSphere(-305.75);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: radius > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSphere26() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_radius = 0;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSphere(mca_radius);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 12.56637061*radius*radius " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSphere27() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_radius = -126.36782858431182;

		double res = testObject.surfaceAreaOfSphere(mca_radius);
		org.junit.Assert.assertEquals(200670.21835382425, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: radius > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSphere28() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_radius = 0;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSphere(mca_radius);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSphere29() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.surfaceAreaOfSphere(243.36);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: radius > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSphere30() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_radius = 0;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSphere(mca_radius);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 12.56637061*radius*radius " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSphere31() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_radius = 77.90539031794822;

		double res = testObject.surfaceAreaOfSphere(mca_radius);
		org.junit.Assert.assertEquals(76268.44518856816, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: radius > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSphere32() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_radius = -1;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSphere(mca_radius);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSphere33() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.surfaceAreaOfSphere(-267.78);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: radius > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSphere34() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_radius = -1;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSphere(mca_radius);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 12.56637061*radius*radius " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSphere35() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_radius = -202.22763687734775;

		double res = testObject.surfaceAreaOfSphere(mca_radius);
		org.junit.Assert.assertEquals(513914.5235145274, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: radius > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSphere36() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_radius = 0;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSphere(mca_radius);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSphere37() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.surfaceAreaOfSphere(274.78);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: radius > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSphere38() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_radius = 0;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSphere(mca_radius);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 12.56637061*radius*radius " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSphere39() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_radius = 169.01286942657896;

		double res = testObject.surfaceAreaOfSphere(mca_radius);
		org.junit.Assert.assertEquals(358962.7862445339, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: radius > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSphere40() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_radius = -1;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSphere(mca_radius);
	};

};
