import org.ktu.examples.GeometryCalculator;
import org.junit.rules.ExpectedException;
import org.junit.Rule;
public class TestvolumeOfRectangularPrism
{
@Rule
 public final ExpectedException exception = ExpectedException.none();
/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism1() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.volumeOfRectangularPrism(91.57, -129.63, 75.76);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: length > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism2() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_length = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(mca_length, 0.00, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism3() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(0.00, mca_height, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: width > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism4() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_width = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(0.00, 0.00, mca_width);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = length*height*width " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism5() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_length = -269.95638840528056;
		double mca_height = -594.5885515310922;
		double mca_width = -254.8800516499903;

		double res = testObject.volumeOfRectangularPrism(mca_length, mca_height, mca_width);
		org.junit.Assert.assertEquals(-4.091155611254622E7, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: length > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism6() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_length = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(mca_length, 0.00, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism7() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(0.00, mca_height, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: width > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism8() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_width = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(0.00, 0.00, mca_width);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism9() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.volumeOfRectangularPrism(-2.61, -166.50, 26.11);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: length > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism10() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_length = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(mca_length, 0.00, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism11() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(0.00, mca_height, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: width > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism12() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_width = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(0.00, 0.00, mca_width);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = length*height*width " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism13() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_length = 63.12742001765156;
		double mca_height = 21.19231845649921;
		double mca_width = -138.5131228596035;

		double res = testObject.volumeOfRectangularPrism(mca_length, mca_height, mca_width);
		org.junit.Assert.assertEquals(-185305.12576328838, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: length > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism14() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_length = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(mca_length, 0.00, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism15() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(0.00, mca_height, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: width > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism16() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_width = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(0.00, 0.00, mca_width);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism17() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.volumeOfRectangularPrism(-378.03, -456.27, 23.67);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: length > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism18() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_length = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(mca_length, 0.00, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism19() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(0.00, mca_height, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: width > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism20() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_width = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(0.00, 0.00, mca_width);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = length*height*width " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism21() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_length = -167.6725028216149;
		double mca_height = 3.898404607803755;
		double mca_width = -0.3799183626567668;

		double res = testObject.volumeOfRectangularPrism(mca_length, mca_height, mca_width);
		org.junit.Assert.assertEquals(248.3356352100522, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: length > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism22() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_length = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(mca_length, 0.00, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism23() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(0.00, mca_height, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: width > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism24() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_width = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(0.00, 0.00, mca_width);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism25() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.volumeOfRectangularPrism(-248.46, -158.67, -231.30);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: length > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism26() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_length = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(mca_length, 0.00, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism27() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(0.00, mca_height, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: width > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism28() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_width = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(0.00, 0.00, mca_width);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = length*height*width " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism29() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_length = 177.51073756817186;
		double mca_height = -152.2729217444454;
		double mca_width = 49.283931087450014;

		double res = testObject.volumeOfRectangularPrism(mca_length, mca_height, mca_width);
		org.junit.Assert.assertEquals(-1332148.5335004346, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: length > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism30() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_length = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(mca_length, 0.00, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism31() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(0.00, mca_height, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: width > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism32() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_width = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(0.00, 0.00, mca_width);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism33() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.volumeOfRectangularPrism(133.21, -44.97, -147.28);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: length > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism34() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_length = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(mca_length, 0.00, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism35() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(0.00, mca_height, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: width > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism36() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_width = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(0.00, 0.00, mca_width);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = length*height*width " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism37() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_length = -200.5092000801576;
		double mca_height = -91.99681680041992;
		double mca_width = -374.7387525765609;

		double res = testObject.volumeOfRectangularPrism(mca_length, mca_height, mca_width);
		org.junit.Assert.assertEquals(-6912509.030614362, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: length > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism38() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_length = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(mca_length, 0.00, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism39() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(0.00, mca_height, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: width > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism40() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_width = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(0.00, 0.00, mca_width);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism41() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.volumeOfRectangularPrism(-130.97, 364.82, -146.66);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: length > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism42() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_length = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(mca_length, 0.00, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism43() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(0.00, mca_height, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: width > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism44() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_width = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(0.00, 0.00, mca_width);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = length*height*width " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism45() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_length = -138.75979343118578;
		double mca_height = -16.97714326672424;
		double mca_width = -548.8433794307434;

		double res = testObject.volumeOfRectangularPrism(mca_length, mca_height, mca_width);
		org.junit.Assert.assertEquals(-1292934.9880093995, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: length > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism46() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_length = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(mca_length, 0.00, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism47() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(0.00, mca_height, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: width > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism48() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_width = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(0.00, 0.00, mca_width);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism49() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.volumeOfRectangularPrism(-83.50, 221.12, 131.44);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: length > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism50() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_length = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(mca_length, 0.00, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism51() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(0.00, mca_height, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: width > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism52() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_width = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(0.00, 0.00, mca_width);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = length*height*width " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism53() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_length = -127.81557570475158;
		double mca_height = -348.6661639255575;
		double mca_width = -198.53714979824127;

		double res = testObject.volumeOfRectangularPrism(mca_length, mca_height, mca_width);
		org.junit.Assert.assertEquals(-8847801.42398914, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: length > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism54() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_length = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(mca_length, 0.00, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism55() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(0.00, mca_height, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: width > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism56() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_width = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(0.00, 0.00, mca_width);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism57() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.volumeOfRectangularPrism(-101.77, 67.15, -90.50);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: length > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism58() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_length = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(mca_length, 0.00, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism59() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(0.00, mca_height, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: width > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism60() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_width = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(0.00, 0.00, mca_width);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = length*height*width " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism61() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_length = -210.74637471424012;
		double mca_height = -427.7023123959409;
		double mca_width = -444.69158380338104;

		double res = testObject.volumeOfRectangularPrism(mca_length, mca_height, mca_width);
		org.junit.Assert.assertEquals(-4.008303712665481E7, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: length > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism62() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_length = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(mca_length, 0.00, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism63() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(0.00, mca_height, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: width > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism64() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_width = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(0.00, 0.00, mca_width);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism65() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.volumeOfRectangularPrism(45.21, -57.52, -60.17);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: length > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism66() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_length = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(mca_length, 0.00, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism67() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(0.00, mca_height, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: width > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism68() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_width = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(0.00, 0.00, mca_width);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = length*height*width " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism69() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_length = 36.743368392218514;
		double mca_height = -257.0072421210762;
		double mca_width = -398.60334134489756;

		double res = testObject.volumeOfRectangularPrism(mca_length, mca_height, mca_width);
		org.junit.Assert.assertEquals(3764135.6275633303, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: length > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism70() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_length = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(mca_length, 0.00, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism71() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(0.00, mca_height, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: width > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism72() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_width = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(0.00, 0.00, mca_width);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism73() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.volumeOfRectangularPrism(-136.52, -231.78, 6.86);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: length > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism74() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_length = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(mca_length, 0.00, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism75() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(0.00, mca_height, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: width > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism76() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_width = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(0.00, 0.00, mca_width);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = length*height*width " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism77() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_length = 163.01618639773608;
		double mca_height = -185.19144911874855;
		double mca_width = -154.16367286949142;

		double res = testObject.volumeOfRectangularPrism(mca_length, mca_height, mca_width);
		org.junit.Assert.assertEquals(4654078.537088326, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: length > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism78() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_length = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(mca_length, 0.00, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism79() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(0.00, mca_height, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: width > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRectangularPrism80() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_width = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRectangularPrism(0.00, 0.00, mca_width);
	};

};
