import org.ktu.examples.GeometryCalculator;
import org.junit.rules.ExpectedException;
import org.junit.Rule;
public class TestvolumeOfRightCircularCone
{
@Rule
 public final ExpectedException exception = ExpectedException.none();
/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone1() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.volumeOfRightCircularCone(-215.01, -125.02);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone2() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRightCircularCone(0.00, mca_height);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone3() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRightCircularCone(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 0.333333*areaOfBase*height " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone4() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -299.3901717002559;
		double mca_height = -192.7703955774607;

		double res = testObject.volumeOfRightCircularCone(mca_areaOfBase, mca_height);
		org.junit.Assert.assertEquals(19237.834705700127, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone5() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRightCircularCone(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone6() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRightCircularCone(0.00, mca_height);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone7() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.volumeOfRightCircularCone(-490.68, -256.42);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone8() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRightCircularCone(0.00, mca_height);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone9() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRightCircularCone(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 0.333333*areaOfBase*height " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone10() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -232.77819220541886;
		double mca_height = -212.6049885350562;

		double res = testObject.volumeOfRightCircularCone(mca_areaOfBase, mca_height);
		org.junit.Assert.assertEquals(16496.585131746433, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone11() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRightCircularCone(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone12() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRightCircularCone(0.00, mca_height);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone13() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.volumeOfRightCircularCone(79.61, -49.36);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone14() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRightCircularCone(0.00, mca_height);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone15() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRightCircularCone(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 0.333333*areaOfBase*height " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone16() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -7.580268330533485;
		double mca_height = 45.10738079544038;

		double res = testObject.volumeOfRightCircularCone(mca_areaOfBase, mca_height);
		org.junit.Assert.assertEquals(-113.97523606364697, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone17() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRightCircularCone(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone18() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRightCircularCone(0.00, mca_height);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone19() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.volumeOfRightCircularCone(-64.40, -84.73);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone20() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRightCircularCone(0.00, mca_height);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone21() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRightCircularCone(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 0.333333*areaOfBase*height " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone22() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -76.07270259429308;
		double mca_height = 388.94866396898726;

		double res = testObject.volumeOfRightCircularCone(mca_areaOfBase, mca_height);
		org.junit.Assert.assertEquals(-9862.782150061454, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone23() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRightCircularCone(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone24() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRightCircularCone(0.00, mca_height);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone25() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.volumeOfRightCircularCone(-326.65, 41.69);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone26() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRightCircularCone(0.00, mca_height);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone27() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRightCircularCone(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 0.333333*areaOfBase*height " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone28() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -168.50039423977108;
		double mca_height = -220.7810592906233;

		double res = testObject.volumeOfRightCircularCone(mca_areaOfBase, mca_height);
		org.junit.Assert.assertEquals(12400.552776482922, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone29() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRightCircularCone(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone30() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRightCircularCone(0.00, mca_height);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone31() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.volumeOfRightCircularCone(-255.68, -275.57);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone32() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRightCircularCone(0.00, mca_height);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone33() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRightCircularCone(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 0.333333*areaOfBase*height " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone34() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -186.46820075071264;
		double mca_height = -119.57757089236131;

		double res = testObject.volumeOfRightCircularCone(mca_areaOfBase, mca_height);
		org.junit.Assert.assertEquals(7432.464065674968, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone35() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRightCircularCone(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone36() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRightCircularCone(0.00, mca_height);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone37() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.volumeOfRightCircularCone(-36.76, 77.92);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone38() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRightCircularCone(0.00, mca_height);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone39() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRightCircularCone(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 0.333333*areaOfBase*height " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone40() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 156.31311602208802;
		double mca_height = -181.36923011634156;

		double res = testObject.volumeOfRightCircularCone(mca_areaOfBase, mca_height);
		org.junit.Assert.assertEquals(-9450.12038654099, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone41() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRightCircularCone(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone42() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRightCircularCone(0.00, mca_height);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone43() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.volumeOfRightCircularCone(-72.21, 19.11);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone44() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRightCircularCone(0.00, mca_height);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone45() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRightCircularCone(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 0.333333*areaOfBase*height " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone46() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 95.00739086117574;
		double mca_height = -412.5047904071308;

		double res = testObject.volumeOfRightCircularCone(mca_areaOfBase, mca_height);
		org.junit.Assert.assertEquals(-13063.654887771267, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone47() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRightCircularCone(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone48() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRightCircularCone(0.00, mca_height);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone49() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.volumeOfRightCircularCone(328.95, 129.56);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone50() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRightCircularCone(0.00, mca_height);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone51() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRightCircularCone(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 0.333333*areaOfBase*height " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone52() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 65.21600501235793;
		double mca_height = 43.25441404874201;

		double res = testObject.volumeOfRightCircularCone(mca_areaOfBase, mca_height);
		org.junit.Assert.assertEquals(940.2924208430934, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone53() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRightCircularCone(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone54() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRightCircularCone(0.00, mca_height);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone55() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.volumeOfRightCircularCone(-216.71, -236.46);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone56() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRightCircularCone(0.00, mca_height);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone57() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRightCircularCone(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 0.333333*areaOfBase*height " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone58() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -356.963741957359;
		double mca_height = 479.2607542915043;

		double res = testObject.volumeOfRightCircularCone(mca_areaOfBase, mca_height);
		org.junit.Assert.assertEquals(-57026.180382163184, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone59() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRightCircularCone(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfRightCircularCone60() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfRightCircularCone(0.00, mca_height);
	};

};
