import org.ktu.examples.GeometryCalculator;
import org.junit.rules.ExpectedException;
import org.junit.Rule;
public class TestareaOfTriangle
{
@Rule
 public final ExpectedException exception = ExpectedException.none();
/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testAreaOfTriangle1() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.areaOfTriangle(352.82, 62.49);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: base > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfTriangle2() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_base = -1;
		exception.expect(Throwable.class);

		double res = testObject.areaOfTriangle(mca_base, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfTriangle3() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.areaOfTriangle(0.00, mca_height);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = base*height*0.5 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfTriangle4() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_base = -10.550929689015092;
		double mca_height = 83.047003910379;

		double res = testObject.areaOfTriangle(mca_base, mca_height);
		org.junit.Assert.assertEquals(-438.11154957088513, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: base > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfTriangle5() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_base = -1;
		exception.expect(Throwable.class);

		double res = testObject.areaOfTriangle(mca_base, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfTriangle6() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.areaOfTriangle(0.00, mca_height);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testAreaOfTriangle7() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.areaOfTriangle(100.21, -264.44);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: base > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfTriangle8() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_base = -1;
		exception.expect(Throwable.class);

		double res = testObject.areaOfTriangle(mca_base, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfTriangle9() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.areaOfTriangle(0.00, mca_height);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = base*height*0.5 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfTriangle10() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_base = -172.91333132571765;
		double mca_height = -300.3765485461325;

		double res = testObject.areaOfTriangle(mca_base, mca_height);
		org.junit.Assert.assertEquals(25969.55483061646, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: base > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfTriangle11() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_base = 0;
		exception.expect(Throwable.class);

		double res = testObject.areaOfTriangle(mca_base, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfTriangle12() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.areaOfTriangle(0.00, mca_height);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testAreaOfTriangle13() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.areaOfTriangle(-478.62, -237.95);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: base > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfTriangle14() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_base = -1;
		exception.expect(Throwable.class);

		double res = testObject.areaOfTriangle(mca_base, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfTriangle15() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.areaOfTriangle(0.00, mca_height);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = base*height*0.5 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfTriangle16() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_base = -440.90808906497773;
		double mca_height = -71.15469352856798;

		double res = testObject.areaOfTriangle(mca_base, mca_height);
		org.junit.Assert.assertEquals(15686.339975842522, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: base > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfTriangle17() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_base = -1;
		exception.expect(Throwable.class);

		double res = testObject.areaOfTriangle(mca_base, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfTriangle18() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.areaOfTriangle(0.00, mca_height);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testAreaOfTriangle19() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.areaOfTriangle(-129.09, -45.44);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: base > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfTriangle20() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_base = -1;
		exception.expect(Throwable.class);

		double res = testObject.areaOfTriangle(mca_base, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfTriangle21() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.areaOfTriangle(0.00, mca_height);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = base*height*0.5 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfTriangle22() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_base = -212.6219270066344;
		double mca_height = -339.0127449479743;

		double res = testObject.areaOfTriangle(mca_base, mca_height);
		org.junit.Assert.assertEquals(36040.771555323474, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: base > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfTriangle23() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_base = -1;
		exception.expect(Throwable.class);

		double res = testObject.areaOfTriangle(mca_base, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfTriangle24() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.areaOfTriangle(0.00, mca_height);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testAreaOfTriangle25() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.areaOfTriangle(54.98, -6.33);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: base > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfTriangle26() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_base = -1;
		exception.expect(Throwable.class);

		double res = testObject.areaOfTriangle(mca_base, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfTriangle27() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.areaOfTriangle(0.00, mca_height);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = base*height*0.5 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfTriangle28() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_base = -329.70164556237796;
		double mca_height = -584.4314491207685;

		double res = testObject.areaOfTriangle(mca_base, mca_height);
		org.junit.Assert.assertEquals(96344.00524676128, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: base > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfTriangle29() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_base = 0;
		exception.expect(Throwable.class);

		double res = testObject.areaOfTriangle(mca_base, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfTriangle30() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.areaOfTriangle(0.00, mca_height);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testAreaOfTriangle31() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.areaOfTriangle(11.49, -80.64);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: base > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfTriangle32() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_base = -1;
		exception.expect(Throwable.class);

		double res = testObject.areaOfTriangle(mca_base, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfTriangle33() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.areaOfTriangle(0.00, mca_height);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = base*height*0.5 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfTriangle34() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_base = -235.51971437083657;
		double mca_height = 43.57792454938027;

		double res = testObject.areaOfTriangle(mca_base, mca_height);
		org.junit.Assert.assertEquals(-5131.730171371954, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: base > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfTriangle35() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_base = -1;
		exception.expect(Throwable.class);

		double res = testObject.areaOfTriangle(mca_base, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfTriangle36() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.areaOfTriangle(0.00, mca_height);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testAreaOfTriangle37() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.areaOfTriangle(-265.53, 86.68);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: base > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfTriangle38() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_base = -1;
		exception.expect(Throwable.class);

		double res = testObject.areaOfTriangle(mca_base, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfTriangle39() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.areaOfTriangle(0.00, mca_height);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = base*height*0.5 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfTriangle40() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_base = 112.74650168374077;
		double mca_height = -424.7674501757156;

		double res = testObject.areaOfTriangle(mca_base, mca_height);
		org.junit.Assert.assertEquals(-23945.5220182173, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: base > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfTriangle41() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_base = -1;
		exception.expect(Throwable.class);

		double res = testObject.areaOfTriangle(mca_base, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfTriangle42() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.areaOfTriangle(0.00, mca_height);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testAreaOfTriangle43() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.areaOfTriangle(-221.33, 111.21);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: base > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfTriangle44() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_base = -1;
		exception.expect(Throwable.class);

		double res = testObject.areaOfTriangle(mca_base, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfTriangle45() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.areaOfTriangle(0.00, mca_height);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = base*height*0.5 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfTriangle46() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_base = -190.79030479673136;
		double mca_height = -405.6909714687375;

		double res = testObject.areaOfTriangle(mca_base, mca_height);
		org.junit.Assert.assertEquals(38700.952049901236, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: base > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfTriangle47() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_base = 0;
		exception.expect(Throwable.class);

		double res = testObject.areaOfTriangle(mca_base, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfTriangle48() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.areaOfTriangle(0.00, mca_height);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testAreaOfTriangle49() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.areaOfTriangle(85.33, -218.31);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: base > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfTriangle50() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_base = 0;
		exception.expect(Throwable.class);

		double res = testObject.areaOfTriangle(mca_base, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfTriangle51() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.areaOfTriangle(0.00, mca_height);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = base*height*0.5 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfTriangle52() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_base = -265.43638484912924;
		double mca_height = -143.09661910434704;

		double res = testObject.areaOfTriangle(mca_base, mca_height);
		org.junit.Assert.assertEquals(18991.524629595362, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: base > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfTriangle53() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_base = 0;
		exception.expect(Throwable.class);

		double res = testObject.areaOfTriangle(mca_base, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfTriangle54() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.areaOfTriangle(0.00, mca_height);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testAreaOfTriangle55() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.areaOfTriangle(-32.63, -406.52);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: base > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfTriangle56() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_base = -1;
		exception.expect(Throwable.class);

		double res = testObject.areaOfTriangle(mca_base, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfTriangle57() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.areaOfTriangle(0.00, mca_height);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = base*height*0.5 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfTriangle58() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_base = 25.720795861529425;
		double mca_height = -256.96026105675594;

		double res = testObject.areaOfTriangle(mca_base, mca_height);
		org.junit.Assert.assertEquals(-3304.6112095830645, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: base > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfTriangle59() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_base = -1;
		exception.expect(Throwable.class);

		double res = testObject.areaOfTriangle(mca_base, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfTriangle60() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.areaOfTriangle(0.00, mca_height);
	};

};
