import org.ktu.examples.GeometryCalculator;
import org.junit.rules.ExpectedException;
import org.junit.Rule;
public class TestvolumeOfCylinder
{
@Rule
 public final ExpectedException exception = ExpectedException.none();
/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testVolumeOfCylinder1() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.volumeOfCylinder(-114.98, -166.65);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfCylinder2() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfCylinder(0.00, mca_height);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfCylinder3() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfCylinder(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = areaOfBase*height " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfCylinder4() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 194.77376667502818;
		double mca_height = -211.16269242708645;

		double res = testObject.volumeOfCylinder(mca_areaOfBase, mca_height);
		org.junit.Assert.assertEquals(-41128.95298526408, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfCylinder5() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfCylinder(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfCylinder6() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfCylinder(0.00, mca_height);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testVolumeOfCylinder7() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.volumeOfCylinder(-446.84, 3.43);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfCylinder8() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfCylinder(0.00, mca_height);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfCylinder9() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfCylinder(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = areaOfBase*height " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfCylinder10() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -314.75272038187376;
		double mca_height = -29.668132114459766;

		double res = testObject.volumeOfCylinder(mca_areaOfBase, mca_height);
		org.junit.Assert.assertEquals(9338.125291675044, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfCylinder11() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfCylinder(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfCylinder12() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfCylinder(0.00, mca_height);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testVolumeOfCylinder13() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.volumeOfCylinder(-199.96, -132.47);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfCylinder14() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfCylinder(0.00, mca_height);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfCylinder15() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfCylinder(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = areaOfBase*height " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfCylinder16() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -228.4724496210597;
		double mca_height = -245.9362490205411;

		double res = testObject.volumeOfCylinder(mca_areaOfBase, mca_height);
		org.junit.Assert.assertEquals(56189.65726433797, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfCylinder17() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfCylinder(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfCylinder18() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfCylinder(0.00, mca_height);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testVolumeOfCylinder19() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.volumeOfCylinder(-214.65, -288.90);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfCylinder20() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfCylinder(0.00, mca_height);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfCylinder21() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfCylinder(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = areaOfBase*height " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfCylinder22() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -408.23446715736225;
		double mca_height = -170.34016459301026;

		double res = testObject.volumeOfCylinder(mca_areaOfBase, mca_height);
		org.junit.Assert.assertEquals(69538.72632812493, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfCylinder23() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfCylinder(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfCylinder24() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfCylinder(0.00, mca_height);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testVolumeOfCylinder25() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.volumeOfCylinder(-250.54, -93.26);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfCylinder26() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfCylinder(0.00, mca_height);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfCylinder27() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfCylinder(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = areaOfBase*height " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfCylinder28() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -35.053436325193005;
		double mca_height = -386.6496885199432;

		double res = testObject.volumeOfCylinder(mca_areaOfBase, mca_height);
		org.junit.Assert.assertEquals(13553.400236689538, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfCylinder29() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfCylinder(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfCylinder30() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfCylinder(0.00, mca_height);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testVolumeOfCylinder31() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.volumeOfCylinder(-145.02, -353.09);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfCylinder32() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfCylinder(0.00, mca_height);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfCylinder33() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfCylinder(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = areaOfBase*height " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfCylinder34() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -4.914975387023674;
		double mca_height = 83.57472114586233;

		double res = testObject.volumeOfCylinder(mca_areaOfBase, mca_height);
		org.junit.Assert.assertEquals(-410.7676974092803, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfCylinder35() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfCylinder(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfCylinder36() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfCylinder(0.00, mca_height);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testVolumeOfCylinder37() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.volumeOfCylinder(-97.16, -82.11);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfCylinder38() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfCylinder(0.00, mca_height);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfCylinder39() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfCylinder(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = areaOfBase*height " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfCylinder40() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -165.08288997592422;
		double mca_height = 77.07978628952358;

		double res = testObject.volumeOfCylinder(mca_areaOfBase, mca_height);
		org.junit.Assert.assertEquals(-12724.553879401174, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfCylinder41() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfCylinder(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfCylinder42() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfCylinder(0.00, mca_height);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testVolumeOfCylinder43() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.volumeOfCylinder(-145.27, -280.81);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfCylinder44() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfCylinder(0.00, mca_height);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfCylinder45() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfCylinder(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = areaOfBase*height " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfCylinder46() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 116.95054089227645;
		double mca_height = 91.03602959348422;

		double res = testObject.volumeOfCylinder(mca_areaOfBase, mca_height);
		org.junit.Assert.assertEquals(10646.712901643265, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfCylinder47() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfCylinder(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfCylinder48() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfCylinder(0.00, mca_height);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testVolumeOfCylinder49() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.volumeOfCylinder(328.64, 147.12);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfCylinder50() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfCylinder(0.00, mca_height);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfCylinder51() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfCylinder(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = areaOfBase*height " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfCylinder52() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -247.15601140311452;
		double mca_height = -134.87815928715128;

		double res = testObject.volumeOfCylinder(mca_areaOfBase, mca_height);
		org.junit.Assert.assertEquals(33335.94787480626, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfCylinder53() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfCylinder(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfCylinder54() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfCylinder(0.00, mca_height);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testVolumeOfCylinder55() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.volumeOfCylinder(-302.59, 28.76);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfCylinder56() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfCylinder(0.00, mca_height);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfCylinder57() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfCylinder(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = areaOfBase*height " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfCylinder58() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -419.5798024860541;
		double mca_height = -105.55667383521288;

		double res = testObject.volumeOfCylinder(mca_areaOfBase, mca_height);
		org.junit.Assert.assertEquals(44289.448358863454, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfCylinder59() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfCylinder(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfCylinder60() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfCylinder(0.00, mca_height);
	};

};
