import org.ktu.examples.SimulatedAnnealing;
import org.junit.rules.ExpectedException;
import org.junit.Rule;
public class TestSimulatedAnnealingFields
{
@Rule
 public final ExpectedException exception = ExpectedException.none();
/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields1() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: IGNORE_MANAGER_FLAG
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields2() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: COUNT
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields3() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: randomGen
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields4() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: iCount
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields5() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: curIteration
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields6() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: bestValue
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields7() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: testCase
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields8() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: valuesMatrix
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields9() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: resultsList
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields10() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: IGNORE_MANAGER_FLAG
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields11() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: COUNT
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields12() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: randomGen
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields13() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: iCount
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields14() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: curIteration
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields15() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: bestValue
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields16() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: testCase
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields17() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: valuesMatrix
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields18() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: resultsList
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields19() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: IGNORE_MANAGER_FLAG
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields20() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: COUNT
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields21() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: randomGen
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields22() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: iCount
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields23() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: curIteration
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields24() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: bestValue
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields25() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: testCase
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields26() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: valuesMatrix
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields27() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: resultsList
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields28() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: IGNORE_MANAGER_FLAG
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields29() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: COUNT
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields30() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: randomGen
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields31() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: iCount
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields32() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: curIteration
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields33() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: bestValue
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields34() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: testCase
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields35() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: valuesMatrix
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields36() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: resultsList
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields37() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: IGNORE_MANAGER_FLAG
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields38() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: COUNT
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields39() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: randomGen
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields40() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: iCount
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields41() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: curIteration
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields42() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: bestValue
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields43() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: testCase
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields44() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: valuesMatrix
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields45() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: resultsList
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields46() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: IGNORE_MANAGER_FLAG
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields47() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: COUNT
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields48() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: randomGen
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields49() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: iCount
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields50() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: curIteration
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields51() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: bestValue
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields52() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: testCase
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields53() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: valuesMatrix
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields54() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: resultsList
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields55() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: IGNORE_MANAGER_FLAG
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields56() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: COUNT
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields57() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: randomGen
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields58() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: iCount
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields59() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: curIteration
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields60() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: bestValue
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields61() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: testCase
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields62() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: valuesMatrix
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields63() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: resultsList
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields64() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: IGNORE_MANAGER_FLAG
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields65() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: COUNT
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields66() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: randomGen
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields67() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: iCount
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields68() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: curIteration
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields69() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: bestValue
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields70() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: testCase
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields71() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: valuesMatrix
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields72() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: resultsList
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields73() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: IGNORE_MANAGER_FLAG
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields74() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: COUNT
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields75() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: randomGen
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields76() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: iCount
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields77() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: curIteration
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields78() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: bestValue
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields79() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: testCase
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields80() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: valuesMatrix
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields81() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: resultsList
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields82() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: IGNORE_MANAGER_FLAG
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields83() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: COUNT
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields84() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: randomGen
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields85() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: iCount
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields86() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: curIteration
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields87() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: bestValue
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields88() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: testCase
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields89() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: valuesMatrix
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void SimulatedAnnealingFields90() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
//Cannot produce field assignment: unaccessible variable: resultsList
	};

};
