import org.ktu.examples.GeometryCalculator;
import org.junit.rules.ExpectedException;
import org.junit.Rule;
public class TestsurfaceAreaOfRightCircularCone
{
@Rule
 public final ExpectedException exception = ExpectedException.none();
/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone1() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.surfaceAreaOfRightCircularCone(-40.09, 62.15);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: circumference > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone2() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_circumference = -1;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfRightCircularCone(mca_circumference, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: slantHeight > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone3() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_slantHeight = -1;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfRightCircularCone(0.00, mca_slantHeight);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 0.5*circumference*slantHeight " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone4() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_circumference = -208.4957947088613;
		double mca_slantHeight = -142.01058145742934;

		double res = testObject.surfaceAreaOfRightCircularCone(mca_circumference, mca_slantHeight);
		org.junit.Assert.assertEquals(14804.304519017107, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: circumference > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone5() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_circumference = 0;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfRightCircularCone(mca_circumference, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: slantHeight > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone6() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_slantHeight = 0;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfRightCircularCone(0.00, mca_slantHeight);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone7() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.surfaceAreaOfRightCircularCone(-199.81, 115.57);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: circumference > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone8() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_circumference = 0;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfRightCircularCone(mca_circumference, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: slantHeight > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone9() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_slantHeight = -1;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfRightCircularCone(0.00, mca_slantHeight);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 0.5*circumference*slantHeight " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone10() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_circumference = -187.12601728783412;
		double mca_slantHeight = -368.46049595432277;

		double res = testObject.surfaceAreaOfRightCircularCone(mca_circumference, mca_slantHeight);
		org.junit.Assert.assertEquals(34474.27256791627, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: circumference > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone11() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_circumference = 0;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfRightCircularCone(mca_circumference, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: slantHeight > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone12() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_slantHeight = 0;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfRightCircularCone(0.00, mca_slantHeight);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone13() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.surfaceAreaOfRightCircularCone(-166.26, 259.91);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: circumference > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone14() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_circumference = 0;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfRightCircularCone(mca_circumference, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: slantHeight > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone15() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_slantHeight = 0;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfRightCircularCone(0.00, mca_slantHeight);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 0.5*circumference*slantHeight " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone16() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_circumference = 132.52987010863157;
		double mca_slantHeight = -240.10469841289154;

		double res = testObject.surfaceAreaOfRightCircularCone(mca_circumference, mca_slantHeight);
		org.junit.Assert.assertEquals(-15910.522246566336, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: circumference > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone17() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_circumference = 0;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfRightCircularCone(mca_circumference, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: slantHeight > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone18() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_slantHeight = -1;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfRightCircularCone(0.00, mca_slantHeight);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone19() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.surfaceAreaOfRightCircularCone(-64.04, -177.35);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: circumference > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone20() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_circumference = -1;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfRightCircularCone(mca_circumference, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: slantHeight > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone21() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_slantHeight = 0;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfRightCircularCone(0.00, mca_slantHeight);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 0.5*circumference*slantHeight " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone22() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_circumference = -292.64875765716874;
		double mca_slantHeight = -273.51407533010587;

		double res = testObject.surfaceAreaOfRightCircularCone(mca_circumference, mca_slantHeight);
		org.junit.Assert.assertEquals(40021.77717355237, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: circumference > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone23() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_circumference = -1;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfRightCircularCone(mca_circumference, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: slantHeight > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone24() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_slantHeight = -1;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfRightCircularCone(0.00, mca_slantHeight);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone25() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.surfaceAreaOfRightCircularCone(2.45, -129.86);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: circumference > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone26() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_circumference = -1;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfRightCircularCone(mca_circumference, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: slantHeight > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone27() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_slantHeight = -1;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfRightCircularCone(0.00, mca_slantHeight);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 0.5*circumference*slantHeight " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone28() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_circumference = -140.25236664206363;
		double mca_slantHeight = -81.63554912917263;

		double res = testObject.surfaceAreaOfRightCircularCone(mca_circumference, mca_slantHeight);
		org.junit.Assert.assertEquals(5724.78948374546, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: circumference > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone29() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_circumference = 0;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfRightCircularCone(mca_circumference, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: slantHeight > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone30() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_slantHeight = -1;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfRightCircularCone(0.00, mca_slantHeight);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone31() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.surfaceAreaOfRightCircularCone(-259.01, 129.73);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: circumference > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone32() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_circumference = 0;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfRightCircularCone(mca_circumference, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: slantHeight > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone33() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_slantHeight = -1;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfRightCircularCone(0.00, mca_slantHeight);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 0.5*circumference*slantHeight " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone34() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_circumference = -180.84962905967544;
		double mca_slantHeight = 1.060147512416961;

		double res = testObject.surfaceAreaOfRightCircularCone(mca_circumference, mca_slantHeight);
		org.junit.Assert.assertEquals(-95.86364218457253, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: circumference > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone35() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_circumference = 0;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfRightCircularCone(mca_circumference, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: slantHeight > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone36() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_slantHeight = 0;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfRightCircularCone(0.00, mca_slantHeight);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone37() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.surfaceAreaOfRightCircularCone(-126.22, -139.23);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: circumference > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone38() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_circumference = 0;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfRightCircularCone(mca_circumference, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: slantHeight > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone39() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_slantHeight = -1;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfRightCircularCone(0.00, mca_slantHeight);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 0.5*circumference*slantHeight " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone40() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_circumference = -174.8602036506221;
		double mca_slantHeight = -127.19695698180345;

		double res = testObject.surfaceAreaOfRightCircularCone(mca_circumference, mca_slantHeight);
		org.junit.Assert.assertEquals(11120.842900788786, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: circumference > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone41() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_circumference = -1;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfRightCircularCone(mca_circumference, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: slantHeight > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone42() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_slantHeight = -1;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfRightCircularCone(0.00, mca_slantHeight);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone43() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.surfaceAreaOfRightCircularCone(141.52, -432.28);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: circumference > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone44() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_circumference = 0;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfRightCircularCone(mca_circumference, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: slantHeight > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone45() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_slantHeight = 0;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfRightCircularCone(0.00, mca_slantHeight);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 0.5*circumference*slantHeight " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone46() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_circumference = -235.35994631427843;
		double mca_slantHeight = 67.79543196616152;

		double res = testObject.surfaceAreaOfRightCircularCone(mca_circumference, mca_slantHeight);
		org.junit.Assert.assertEquals(-7978.1646139545455, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: circumference > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone47() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_circumference = 0;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfRightCircularCone(mca_circumference, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: slantHeight > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone48() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_slantHeight = 0;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfRightCircularCone(0.00, mca_slantHeight);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone49() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.surfaceAreaOfRightCircularCone(144.94, -208.49);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: circumference > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone50() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_circumference = -1;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfRightCircularCone(mca_circumference, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: slantHeight > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone51() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_slantHeight = -1;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfRightCircularCone(0.00, mca_slantHeight);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 0.5*circumference*slantHeight " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone52() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_circumference = -11.244913629613023;
		double mca_slantHeight = -460.9837458006736;

		double res = testObject.surfaceAreaOfRightCircularCone(mca_circumference, mca_slantHeight);
		org.junit.Assert.assertEquals(2591.86120309203, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: circumference > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone53() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_circumference = 0;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfRightCircularCone(mca_circumference, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: slantHeight > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone54() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_slantHeight = -1;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfRightCircularCone(0.00, mca_slantHeight);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone55() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.surfaceAreaOfRightCircularCone(314.21, -336.31);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: circumference > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone56() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_circumference = 0;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfRightCircularCone(mca_circumference, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: slantHeight > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone57() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_slantHeight = -1;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfRightCircularCone(0.00, mca_slantHeight);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 0.5*circumference*slantHeight " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone58() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_circumference = 14.596183057268334;
		double mca_slantHeight = -217.86767035308594;

		double res = testObject.surfaceAreaOfRightCircularCone(mca_circumference, mca_slantHeight);
		org.junit.Assert.assertEquals(-1590.0181993671179, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: circumference > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone59() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_circumference = 0;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfRightCircularCone(mca_circumference, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: slantHeight > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfRightCircularCone60() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_slantHeight = 0;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfRightCircularCone(0.00, mca_slantHeight);
	};

};
