import org.ktu.examples.GeometryCalculator;
import org.junit.rules.ExpectedException;
import org.junit.Rule;
public class TestvolumeOfSquarePyramid
{
@Rule
 public final ExpectedException exception = ExpectedException.none();
/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid1() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.volumeOfSquarePyramid(-99.98, 16.85);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid2() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfSquarePyramid(0.00, mca_height);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid3() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfSquarePyramid(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 0.333333*areaOfBase*height " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid4() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -421.4262288878325;
		double mca_height = -38.071492926964325;

		double res = testObject.volumeOfSquarePyramid(mca_areaOfBase, mca_height);
		org.junit.Assert.assertEquals(5348.10321600489, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid5() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfSquarePyramid(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid6() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfSquarePyramid(0.00, mca_height);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid7() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.volumeOfSquarePyramid(34.40, -218.26);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid8() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfSquarePyramid(0.00, mca_height);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid9() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfSquarePyramid(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 0.333333*areaOfBase*height " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid10() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -59.87407178527144;
		double mca_height = -130.62098401061058;

		double res = testObject.volumeOfSquarePyramid(mca_areaOfBase, mca_height);
		org.junit.Assert.assertEquals(2606.9341175013055, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid11() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfSquarePyramid(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid12() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfSquarePyramid(0.00, mca_height);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid13() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.volumeOfSquarePyramid(45.57, 161.14);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid14() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfSquarePyramid(0.00, mca_height);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid15() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfSquarePyramid(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 0.333333*areaOfBase*height " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid16() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -250.5917008740104;
		double mca_height = -496.24526185198033;

		double res = testObject.volumeOfSquarePyramid(mca_areaOfBase, mca_height);
		org.junit.Assert.assertEquals(41451.606621070736, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid17() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfSquarePyramid(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid18() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfSquarePyramid(0.00, mca_height);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid19() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.volumeOfSquarePyramid(31.09, -371.06);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid20() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfSquarePyramid(0.00, mca_height);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid21() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfSquarePyramid(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 0.333333*areaOfBase*height " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid22() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -93.68157885464123;
		double mca_height = 93.63976524903308;

		double res = testObject.volumeOfSquarePyramid(mca_areaOfBase, mca_height);
		org.junit.Assert.assertEquals(-2924.1040932621113, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid23() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfSquarePyramid(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid24() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfSquarePyramid(0.00, mca_height);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid25() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.volumeOfSquarePyramid(-364.57, -6.88);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid26() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfSquarePyramid(0.00, mca_height);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid27() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfSquarePyramid(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 0.333333*areaOfBase*height " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid28() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 67.67455181132365;
		double mca_height = -114.85989548489795;

		double res = testObject.volumeOfSquarePyramid(mca_areaOfBase, mca_height);
		org.junit.Assert.assertEquals(-2591.0280583146655, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid29() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfSquarePyramid(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid30() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfSquarePyramid(0.00, mca_height);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid31() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.volumeOfSquarePyramid(57.16, -150.40);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid32() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfSquarePyramid(0.00, mca_height);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid33() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfSquarePyramid(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 0.333333*areaOfBase*height " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid34() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -228.4266424207366;
		double mca_height = 265.1760574129818;

		double res = testObject.volumeOfSquarePyramid(mca_areaOfBase, mca_height);
		org.junit.Assert.assertEquals(-20191.071957313157, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid35() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfSquarePyramid(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid36() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfSquarePyramid(0.00, mca_height);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid37() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.volumeOfSquarePyramid(-42.61, -116.99);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid38() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfSquarePyramid(0.00, mca_height);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid39() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfSquarePyramid(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 0.333333*areaOfBase*height " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid40() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -88.42443017411175;
		double mca_height = -233.1366298112959;

		double res = testObject.volumeOfSquarePyramid(mca_areaOfBase, mca_height);
		org.junit.Assert.assertEquals(6871.65100960101, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid41() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfSquarePyramid(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid42() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfSquarePyramid(0.00, mca_height);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid43() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.volumeOfSquarePyramid(54.11, -335.10);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid44() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfSquarePyramid(0.00, mca_height);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid45() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfSquarePyramid(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 0.333333*areaOfBase*height " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid46() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 39.99581033107236;
		double mca_height = -383.84183040147593;

		double res = testObject.volumeOfSquarePyramid(mca_areaOfBase, mca_height);
		org.junit.Assert.assertEquals(-5117.349897934677, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid47() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfSquarePyramid(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid48() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfSquarePyramid(0.00, mca_height);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid49() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.volumeOfSquarePyramid(-156.56, -435.18);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid50() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfSquarePyramid(0.00, mca_height);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid51() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfSquarePyramid(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 0.333333*areaOfBase*height " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid52() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 214.58590260200828;
		double mca_height = 143.36033094982614;

		double res = testObject.volumeOfSquarePyramid(mca_areaOfBase, mca_height);
		org.junit.Assert.assertEquals(10254.35841702835, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid53() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfSquarePyramid(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid54() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfSquarePyramid(0.00, mca_height);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid55() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.volumeOfSquarePyramid(-209.03, -374.50);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid56() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfSquarePyramid(0.00, mca_height);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid57() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfSquarePyramid(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 0.333333*areaOfBase*height " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid58() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -94.55446998627149;
		double mca_height = 92.3700056881469;

		double res = testObject.volumeOfSquarePyramid(mca_areaOfBase, mca_height);
		org.junit.Assert.assertEquals(-2911.3293988248943, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid59() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfSquarePyramid(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfSquarePyramid60() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfSquarePyramid(0.00, mca_height);
	};

};
