import org.ktu.examples.GeometryCalculator;
import org.junit.rules.ExpectedException;
import org.junit.Rule;
public class TestvolumeOfGeneralPrism
{
@Rule
 public final ExpectedException exception = ExpectedException.none();
/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism1() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.volumeOfGeneralPrism(30.76, -116.40);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism2() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfGeneralPrism(0.00, mca_height);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism3() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfGeneralPrism(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = areaOfBase*height " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism4() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 113.06200908051002;
		double mca_height = -448.91173682607575;

		double res = testObject.volumeOfGeneralPrism(mca_areaOfBase, mca_height);
		org.junit.Assert.assertEquals(-50754.862865377305, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism5() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfGeneralPrism(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism6() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfGeneralPrism(0.00, mca_height);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism7() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.volumeOfGeneralPrism(172.91, -381.93);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism8() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfGeneralPrism(0.00, mca_height);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism9() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfGeneralPrism(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = areaOfBase*height " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism10() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 289.8416839940802;
		double mca_height = -7.08781212990111;

		double res = testObject.volumeOfGeneralPrism(mca_areaOfBase, mca_height);
		org.junit.Assert.assertEquals(-2054.343403564206, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism11() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfGeneralPrism(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism12() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfGeneralPrism(0.00, mca_height);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism13() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.volumeOfGeneralPrism(-251.57, -86.67);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism14() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfGeneralPrism(0.00, mca_height);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism15() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfGeneralPrism(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = areaOfBase*height " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism16() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -81.45273022333166;
		double mca_height = -172.18195979142988;

		double res = testObject.volumeOfGeneralPrism(mca_areaOfBase, mca_height);
		org.junit.Assert.assertEquals(14024.690720215876, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism17() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfGeneralPrism(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism18() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfGeneralPrism(0.00, mca_height);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism19() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.volumeOfGeneralPrism(-481.12, -201.62);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism20() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfGeneralPrism(0.00, mca_height);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism21() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfGeneralPrism(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = areaOfBase*height " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism22() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -47.18126988490867;
		double mca_height = -199.40573941459357;

		double res = testObject.volumeOfGeneralPrism(mca_areaOfBase, mca_height);
		org.junit.Assert.assertEquals(9408.21600791971, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism23() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfGeneralPrism(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism24() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfGeneralPrism(0.00, mca_height);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism25() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.volumeOfGeneralPrism(113.51, -389.79);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism26() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfGeneralPrism(0.00, mca_height);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism27() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfGeneralPrism(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = areaOfBase*height " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism28() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -140.07843353556268;
		double mca_height = -192.3904637432969;

		double res = testObject.volumeOfGeneralPrism(mca_areaOfBase, mca_height);
		org.junit.Assert.assertEquals(26949.754788341495, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism29() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfGeneralPrism(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism30() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfGeneralPrism(0.00, mca_height);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism31() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.volumeOfGeneralPrism(-133.17, -138.94);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism32() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfGeneralPrism(0.00, mca_height);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism33() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfGeneralPrism(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = areaOfBase*height " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism34() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 161.0987980396336;
		double mca_height = -52.98849078942434;

		double res = testObject.volumeOfGeneralPrism(mca_areaOfBase, mca_height);
		org.junit.Assert.assertEquals(-8536.382176110457, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism35() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfGeneralPrism(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism36() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfGeneralPrism(0.00, mca_height);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism37() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.volumeOfGeneralPrism(-145.56, -155.98);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism38() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfGeneralPrism(0.00, mca_height);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism39() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfGeneralPrism(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = areaOfBase*height " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism40() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 67.51261219893269;
		double mca_height = -97.75162731080187;

		double res = testObject.volumeOfGeneralPrism(mca_areaOfBase, mca_height);
		org.junit.Assert.assertEquals(-6599.467706448763, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism41() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfGeneralPrism(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism42() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfGeneralPrism(0.00, mca_height);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism43() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.volumeOfGeneralPrism(-317.69, -46.57);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism44() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfGeneralPrism(0.00, mca_height);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism45() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfGeneralPrism(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = areaOfBase*height " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism46() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -46.85001854648594;
		double mca_height = -48.680858197399914;

		double res = testObject.volumeOfGeneralPrism(mca_areaOfBase, mca_height);
		org.junit.Assert.assertEquals(2280.699109407038, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism47() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfGeneralPrism(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism48() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfGeneralPrism(0.00, mca_height);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism49() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.volumeOfGeneralPrism(-224.10, -13.75);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism50() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfGeneralPrism(0.00, mca_height);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism51() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfGeneralPrism(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = areaOfBase*height " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism52() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -80.442508259992;
		double mca_height = 156.8747684477205;

		double res = testObject.volumeOfGeneralPrism(mca_areaOfBase, mca_height);
		org.junit.Assert.assertEquals(-12619.399856640088, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism53() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfGeneralPrism(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism54() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfGeneralPrism(0.00, mca_height);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism55() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.volumeOfGeneralPrism(-335.40, 51.40);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism56() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = -1;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfGeneralPrism(0.00, mca_height);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism57() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfGeneralPrism(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = areaOfBase*height " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism58() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = -234.1112592279232;
		double mca_height = -236.9445148527246;

		double res = testObject.volumeOfGeneralPrism(mca_areaOfBase, mca_height);
		org.junit.Assert.assertEquals(55471.37873932071, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: areaOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism59() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_areaOfBase = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfGeneralPrism(mca_areaOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: height > 0 " is satisfied. 
*/	@org.junit.Test
	public void testVolumeOfGeneralPrism60() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_height = 0;
		exception.expect(Throwable.class);

		double res = testObject.volumeOfGeneralPrism(0.00, mca_height);
	};

};
