import org.ktu.examples.GeometryCalculator;
import org.junit.rules.ExpectedException;
import org.junit.Rule;
public class TestsurfaceAreaOfSquarePyramid
{
@Rule
 public final ExpectedException exception = ExpectedException.none();
/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid1() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.surfaceAreaOfSquarePyramid(187.06, 76.44);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: perimeterOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid2() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_perimeterOfBase = 0;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSquarePyramid(mca_perimeterOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: slantHeight > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid3() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_slantHeight = -1;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSquarePyramid(0.00, mca_slantHeight);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 0.5*perimeterOfBase*slantHeight " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid4() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_perimeterOfBase = 57.82496510487397;
		double mca_slantHeight = 246.10874626499395;

		double res = testObject.surfaceAreaOfSquarePyramid(mca_perimeterOfBase, mca_slantHeight);
		org.junit.Assert.assertEquals(7115.614832388778, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: perimeterOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid5() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_perimeterOfBase = 0;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSquarePyramid(mca_perimeterOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: slantHeight > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid6() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_slantHeight = 0;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSquarePyramid(0.00, mca_slantHeight);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid7() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.surfaceAreaOfSquarePyramid(6.98, 504.99);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: perimeterOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid8() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_perimeterOfBase = 0;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSquarePyramid(mca_perimeterOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: slantHeight > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid9() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_slantHeight = -1;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSquarePyramid(0.00, mca_slantHeight);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 0.5*perimeterOfBase*slantHeight " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid10() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_perimeterOfBase = -193.92086876152126;
		double mca_slantHeight = 179.63804561418783;

		double res = testObject.surfaceAreaOfSquarePyramid(mca_perimeterOfBase, mca_slantHeight);
		org.junit.Assert.assertEquals(-17417.782934062543, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: perimeterOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid11() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_perimeterOfBase = -1;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSquarePyramid(mca_perimeterOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: slantHeight > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid12() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_slantHeight = 0;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSquarePyramid(0.00, mca_slantHeight);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid13() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.surfaceAreaOfSquarePyramid(-61.22, -215.55);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: perimeterOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid14() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_perimeterOfBase = -1;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSquarePyramid(mca_perimeterOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: slantHeight > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid15() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_slantHeight = -1;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSquarePyramid(0.00, mca_slantHeight);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 0.5*perimeterOfBase*slantHeight " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid16() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_perimeterOfBase = -117.70185014147849;
		double mca_slantHeight = -0.6073870792371139;

		double res = testObject.surfaceAreaOfSquarePyramid(mca_perimeterOfBase, mca_slantHeight);
		org.junit.Assert.assertEquals(35.74529148911855, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: perimeterOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid17() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_perimeterOfBase = -1;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSquarePyramid(mca_perimeterOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: slantHeight > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid18() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_slantHeight = -1;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSquarePyramid(0.00, mca_slantHeight);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid19() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.surfaceAreaOfSquarePyramid(-19.85, -304.20);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: perimeterOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid20() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_perimeterOfBase = -1;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSquarePyramid(mca_perimeterOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: slantHeight > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid21() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_slantHeight = -1;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSquarePyramid(0.00, mca_slantHeight);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 0.5*perimeterOfBase*slantHeight " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid22() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_perimeterOfBase = 100.36138889971386;
		double mca_slantHeight = -37.74887824734168;

		double res = testObject.surfaceAreaOfSquarePyramid(mca_perimeterOfBase, mca_slantHeight);
		org.junit.Assert.assertEquals(-1894.2649251547036, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: perimeterOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid23() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_perimeterOfBase = -1;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSquarePyramid(mca_perimeterOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: slantHeight > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid24() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_slantHeight = -1;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSquarePyramid(0.00, mca_slantHeight);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid25() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.surfaceAreaOfSquarePyramid(307.37, -63.77);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: perimeterOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid26() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_perimeterOfBase = 0;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSquarePyramid(mca_perimeterOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: slantHeight > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid27() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_slantHeight = 0;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSquarePyramid(0.00, mca_slantHeight);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 0.5*perimeterOfBase*slantHeight " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid28() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_perimeterOfBase = -21.89237566962852;
		double mca_slantHeight = -242.8774341688569;

		double res = testObject.surfaceAreaOfSquarePyramid(mca_perimeterOfBase, mca_slantHeight);
		org.junit.Assert.assertEquals(2658.582015250043, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: perimeterOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid29() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_perimeterOfBase = -1;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSquarePyramid(mca_perimeterOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: slantHeight > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid30() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_slantHeight = 0;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSquarePyramid(0.00, mca_slantHeight);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid31() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.surfaceAreaOfSquarePyramid(-323.28, -271.23);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: perimeterOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid32() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_perimeterOfBase = -1;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSquarePyramid(mca_perimeterOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: slantHeight > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid33() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_slantHeight = -1;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSquarePyramid(0.00, mca_slantHeight);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 0.5*perimeterOfBase*slantHeight " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid34() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_perimeterOfBase = -32.45891465604892;
		double mca_slantHeight = -96.14914868030411;

		double res = testObject.surfaceAreaOfSquarePyramid(mca_perimeterOfBase, mca_slantHeight);
		org.junit.Assert.assertEquals(1560.4485056328747, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: perimeterOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid35() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_perimeterOfBase = -1;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSquarePyramid(mca_perimeterOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: slantHeight > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid36() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_slantHeight = 0;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSquarePyramid(0.00, mca_slantHeight);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid37() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.surfaceAreaOfSquarePyramid(-56.86, -145.28);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: perimeterOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid38() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_perimeterOfBase = 0;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSquarePyramid(mca_perimeterOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: slantHeight > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid39() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_slantHeight = 0;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSquarePyramid(0.00, mca_slantHeight);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 0.5*perimeterOfBase*slantHeight " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid40() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_perimeterOfBase = -231.4061510052694;
		double mca_slantHeight = 73.18305238913786;

		double res = testObject.surfaceAreaOfSquarePyramid(mca_perimeterOfBase, mca_slantHeight);
		org.junit.Assert.assertEquals(-8467.504236093688, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: perimeterOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid41() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_perimeterOfBase = 0;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSquarePyramid(mca_perimeterOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: slantHeight > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid42() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_slantHeight = -1;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSquarePyramid(0.00, mca_slantHeight);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid43() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.surfaceAreaOfSquarePyramid(-40.34, 4.57);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: perimeterOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid44() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_perimeterOfBase = 0;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSquarePyramid(mca_perimeterOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: slantHeight > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid45() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_slantHeight = -1;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSquarePyramid(0.00, mca_slantHeight);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 0.5*perimeterOfBase*slantHeight " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid46() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_perimeterOfBase = -101.16566354473731;
		double mca_slantHeight = -238.33546034124532;

		double res = testObject.surfaceAreaOfSquarePyramid(mca_perimeterOfBase, mca_slantHeight);
		org.junit.Assert.assertEquals(12055.682495831254, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: perimeterOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid47() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_perimeterOfBase = 0;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSquarePyramid(mca_perimeterOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: slantHeight > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid48() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_slantHeight = 0;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSquarePyramid(0.00, mca_slantHeight);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid49() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.surfaceAreaOfSquarePyramid(-118.73, -333.89);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: perimeterOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid50() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_perimeterOfBase = -1;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSquarePyramid(mca_perimeterOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: slantHeight > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid51() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_slantHeight = 0;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSquarePyramid(0.00, mca_slantHeight);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 0.5*perimeterOfBase*slantHeight " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid52() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_perimeterOfBase = -460.3998742005002;
		double mca_slantHeight = -152.4194326857713;

		double res = testObject.surfaceAreaOfSquarePyramid(mca_perimeterOfBase, mca_slantHeight);
		org.junit.Assert.assertEquals(35086.94381712036, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: perimeterOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid53() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_perimeterOfBase = -1;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSquarePyramid(mca_perimeterOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: slantHeight > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid54() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_slantHeight = -1;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSquarePyramid(0.00, mca_slantHeight);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid55() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.surfaceAreaOfSquarePyramid(-237.91, -70.72);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: perimeterOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid56() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_perimeterOfBase = 0;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSquarePyramid(mca_perimeterOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: slantHeight > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid57() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_slantHeight = -1;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSquarePyramid(0.00, mca_slantHeight);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = 0.5*perimeterOfBase*slantHeight " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid58() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_perimeterOfBase = -128.7679047412497;
		double mca_slantHeight = -27.052346446671365;

		double res = testObject.surfaceAreaOfSquarePyramid(mca_perimeterOfBase, mca_slantHeight);
		org.junit.Assert.assertEquals(1741.7369851361316, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: perimeterOfBase > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid59() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_perimeterOfBase = -1;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSquarePyramid(mca_perimeterOfBase, 0.00);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: slantHeight > 0 " is satisfied. 
*/	@org.junit.Test
	public void testSurfaceAreaOfSquarePyramid60() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_slantHeight = -1;
		exception.expect(Throwable.class);

		double res = testObject.surfaceAreaOfSquarePyramid(0.00, mca_slantHeight);
	};

};
