import org.ktu.examples.GeometryCalculator;
import org.junit.rules.ExpectedException;
import org.junit.Rule;
public class TestareaOfSquare
{
@Rule
 public final ExpectedException exception = ExpectedException.none();
/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testAreaOfSquare1() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.areaOfSquare(84.51);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: a > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfSquare2() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = -1;
		exception.expect(Throwable.class);

		double res = testObject.areaOfSquare(mca_a);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = a*a " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfSquare3() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = -426.58884719813955;

		double res = testObject.areaOfSquare(mca_a);
		org.junit.Assert.assertEquals(181978.04455383765, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: a > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfSquare4() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = 0;
		exception.expect(Throwable.class);

		double res = testObject.areaOfSquare(mca_a);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testAreaOfSquare5() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.areaOfSquare(-108.06);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: a > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfSquare6() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = 0;
		exception.expect(Throwable.class);

		double res = testObject.areaOfSquare(mca_a);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = a*a " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfSquare7() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = -438.20943226221925;

		double res = testObject.areaOfSquare(mca_a);
		org.junit.Assert.assertEquals(192027.50652357654, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: a > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfSquare8() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = 0;
		exception.expect(Throwable.class);

		double res = testObject.areaOfSquare(mca_a);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testAreaOfSquare9() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.areaOfSquare(-236.27);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: a > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfSquare10() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = 0;
		exception.expect(Throwable.class);

		double res = testObject.areaOfSquare(mca_a);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = a*a " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfSquare11() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = 258.7931678566309;

		double res = testObject.areaOfSquare(mca_a);
		org.junit.Assert.assertEquals(66973.90372927033, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: a > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfSquare12() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = 0;
		exception.expect(Throwable.class);

		double res = testObject.areaOfSquare(mca_a);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testAreaOfSquare13() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.areaOfSquare(-0.95);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: a > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfSquare14() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = 0;
		exception.expect(Throwable.class);

		double res = testObject.areaOfSquare(mca_a);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = a*a " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfSquare15() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = -30.88419257302253;

		double res = testObject.areaOfSquare(mca_a);
		org.junit.Assert.assertEquals(953.8333508875401, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: a > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfSquare16() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = 0;
		exception.expect(Throwable.class);

		double res = testObject.areaOfSquare(mca_a);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testAreaOfSquare17() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.areaOfSquare(76.58);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: a > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfSquare18() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = 0;
		exception.expect(Throwable.class);

		double res = testObject.areaOfSquare(mca_a);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = a*a " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfSquare19() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = -163.67698501931503;

		double res = testObject.areaOfSquare(mca_a);
		org.junit.Assert.assertEquals(26790.155425013076, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: a > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfSquare20() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = 0;
		exception.expect(Throwable.class);

		double res = testObject.areaOfSquare(mca_a);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testAreaOfSquare21() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.areaOfSquare(-413.70);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: a > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfSquare22() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = -1;
		exception.expect(Throwable.class);

		double res = testObject.areaOfSquare(mca_a);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = a*a " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfSquare23() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = 235.64263006348568;

		double res = testObject.areaOfSquare(mca_a);
		org.junit.Assert.assertEquals(55527.449103236766, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: a > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfSquare24() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = -1;
		exception.expect(Throwable.class);

		double res = testObject.areaOfSquare(mca_a);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testAreaOfSquare25() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.areaOfSquare(79.13);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: a > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfSquare26() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = -1;
		exception.expect(Throwable.class);

		double res = testObject.areaOfSquare(mca_a);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = a*a " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfSquare27() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = -267.1543989237655;

		double res = testObject.areaOfSquare(mca_a);
		org.junit.Assert.assertEquals(71371.47286431844, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: a > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfSquare28() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = -1;
		exception.expect(Throwable.class);

		double res = testObject.areaOfSquare(mca_a);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testAreaOfSquare29() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.areaOfSquare(-263.49);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: a > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfSquare30() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = 0;
		exception.expect(Throwable.class);

		double res = testObject.areaOfSquare(mca_a);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = a*a " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfSquare31() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = -346.16030299374404;

		double res = testObject.areaOfSquare(mca_a);
		org.junit.Assert.assertEquals(119826.95536872068, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: a > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfSquare32() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = 0;
		exception.expect(Throwable.class);

		double res = testObject.areaOfSquare(mca_a);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testAreaOfSquare33() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.areaOfSquare(320.03);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: a > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfSquare34() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = -1;
		exception.expect(Throwable.class);

		double res = testObject.areaOfSquare(mca_a);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = a*a " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfSquare35() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = -323.1605249731461;

		double res = testObject.areaOfSquare(mca_a);
		org.junit.Assert.assertEquals(104432.72490091938, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: a > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfSquare36() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = 0;
		exception.expect(Throwable.class);

		double res = testObject.areaOfSquare(mca_a);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testAreaOfSquare37() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();

		double res = testObject.areaOfSquare(-110.87);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: a > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfSquare38() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = 0;
		exception.expect(Throwable.class);

		double res = testObject.areaOfSquare(mca_a);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  post: result = a*a " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfSquare39() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = -237.10791710027027;

		double res = testObject.areaOfSquare(mca_a);
		org.junit.Assert.assertEquals(56220.16435162864, res, 0.001);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: a > 0 " is satisfied. 
*/	@org.junit.Test
	public void testAreaOfSquare40() throws Throwable
	{
		GeometryCalculator testObject = new GeometryCalculator();
		double mca_a = 0;
		exception.expect(Throwable.class);

		double res = testObject.areaOfSquare(mca_a);
	};

};
