import org.ktu.examples.SimulatedAnnealing;
import org.junit.rules.ExpectedException;
import org.junit.Rule;
public class Testapply
{
@Rule
 public final ExpectedException exception = ExpectedException.none();
/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testApply1() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();

		testObject.apply(-90.61);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: targetValue >= 0 " is satisfied. 
*/	@org.junit.Test
	public void testApply2() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_targetValue = -1;
		exception.expect(Throwable.class);

		testObject.apply(mca_targetValue);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: targetValue <= 50 " is satisfied. 
*/	@org.junit.Test
	public void testApply3() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_targetValue = 51;
		exception.expect(Throwable.class);

		testObject.apply(mca_targetValue);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: targetValue >= 0 " is satisfied. 
*/	@org.junit.Test
	public void testApply4() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_targetValue = -1;
		exception.expect(Throwable.class);

		testObject.apply(mca_targetValue);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: targetValue <= 50 " is satisfied. 
*/	@org.junit.Test
	public void testApply5() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_targetValue = 51;
		exception.expect(Throwable.class);

		testObject.apply(mca_targetValue);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testApply6() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();

		testObject.apply(70.45);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: targetValue >= 0 " is satisfied. 
*/	@org.junit.Test
	public void testApply7() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_targetValue = -1;
		exception.expect(Throwable.class);

		testObject.apply(mca_targetValue);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: targetValue <= 50 " is satisfied. 
*/	@org.junit.Test
	public void testApply8() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_targetValue = 51;
		exception.expect(Throwable.class);

		testObject.apply(mca_targetValue);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: targetValue >= 0 " is satisfied. 
*/	@org.junit.Test
	public void testApply9() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_targetValue = -1;
		exception.expect(Throwable.class);

		testObject.apply(mca_targetValue);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: targetValue <= 50 " is satisfied. 
*/	@org.junit.Test
	public void testApply10() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_targetValue = 51;
		exception.expect(Throwable.class);

		testObject.apply(mca_targetValue);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testApply11() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();

		testObject.apply(-98.62);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: targetValue >= 0 " is satisfied. 
*/	@org.junit.Test
	public void testApply12() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_targetValue = -1;
		exception.expect(Throwable.class);

		testObject.apply(mca_targetValue);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: targetValue <= 50 " is satisfied. 
*/	@org.junit.Test
	public void testApply13() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_targetValue = 51;
		exception.expect(Throwable.class);

		testObject.apply(mca_targetValue);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: targetValue >= 0 " is satisfied. 
*/	@org.junit.Test
	public void testApply14() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_targetValue = -1;
		exception.expect(Throwable.class);

		testObject.apply(mca_targetValue);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: targetValue <= 50 " is satisfied. 
*/	@org.junit.Test
	public void testApply15() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_targetValue = 51;
		exception.expect(Throwable.class);

		testObject.apply(mca_targetValue);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testApply16() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();

		testObject.apply(-420.19);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: targetValue >= 0 " is satisfied. 
*/	@org.junit.Test
	public void testApply17() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_targetValue = -1;
		exception.expect(Throwable.class);

		testObject.apply(mca_targetValue);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: targetValue <= 50 " is satisfied. 
*/	@org.junit.Test
	public void testApply18() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_targetValue = 51;
		exception.expect(Throwable.class);

		testObject.apply(mca_targetValue);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: targetValue >= 0 " is satisfied. 
*/	@org.junit.Test
	public void testApply19() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_targetValue = -1;
		exception.expect(Throwable.class);

		testObject.apply(mca_targetValue);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: targetValue <= 50 " is satisfied. 
*/	@org.junit.Test
	public void testApply20() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_targetValue = 51;
		exception.expect(Throwable.class);

		testObject.apply(mca_targetValue);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testApply21() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();

		testObject.apply(-315.17);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: targetValue >= 0 " is satisfied. 
*/	@org.junit.Test
	public void testApply22() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_targetValue = -1;
		exception.expect(Throwable.class);

		testObject.apply(mca_targetValue);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: targetValue <= 50 " is satisfied. 
*/	@org.junit.Test
	public void testApply23() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_targetValue = 51;
		exception.expect(Throwable.class);

		testObject.apply(mca_targetValue);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: targetValue >= 0 " is satisfied. 
*/	@org.junit.Test
	public void testApply24() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_targetValue = -1;
		exception.expect(Throwable.class);

		testObject.apply(mca_targetValue);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: targetValue <= 50 " is satisfied. 
*/	@org.junit.Test
	public void testApply25() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_targetValue = 51;
		exception.expect(Throwable.class);

		testObject.apply(mca_targetValue);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testApply26() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();

		testObject.apply(-299.85);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: targetValue >= 0 " is satisfied. 
*/	@org.junit.Test
	public void testApply27() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_targetValue = -1;
		exception.expect(Throwable.class);

		testObject.apply(mca_targetValue);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: targetValue <= 50 " is satisfied. 
*/	@org.junit.Test
	public void testApply28() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_targetValue = 51;
		exception.expect(Throwable.class);

		testObject.apply(mca_targetValue);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: targetValue >= 0 " is satisfied. 
*/	@org.junit.Test
	public void testApply29() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_targetValue = -1;
		exception.expect(Throwable.class);

		testObject.apply(mca_targetValue);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: targetValue <= 50 " is satisfied. 
*/	@org.junit.Test
	public void testApply30() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_targetValue = 51;
		exception.expect(Throwable.class);

		testObject.apply(mca_targetValue);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testApply31() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();

		testObject.apply(-142.99);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: targetValue >= 0 " is satisfied. 
*/	@org.junit.Test
	public void testApply32() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_targetValue = -1;
		exception.expect(Throwable.class);

		testObject.apply(mca_targetValue);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: targetValue <= 50 " is satisfied. 
*/	@org.junit.Test
	public void testApply33() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_targetValue = 51;
		exception.expect(Throwable.class);

		testObject.apply(mca_targetValue);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: targetValue >= 0 " is satisfied. 
*/	@org.junit.Test
	public void testApply34() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_targetValue = -1;
		exception.expect(Throwable.class);

		testObject.apply(mca_targetValue);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: targetValue <= 50 " is satisfied. 
*/	@org.junit.Test
	public void testApply35() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_targetValue = 51;
		exception.expect(Throwable.class);

		testObject.apply(mca_targetValue);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testApply36() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();

		testObject.apply(33.30);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: targetValue >= 0 " is satisfied. 
*/	@org.junit.Test
	public void testApply37() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_targetValue = -1;
		exception.expect(Throwable.class);

		testObject.apply(mca_targetValue);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: targetValue <= 50 " is satisfied. 
*/	@org.junit.Test
	public void testApply38() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_targetValue = 51;
		exception.expect(Throwable.class);

		testObject.apply(mca_targetValue);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: targetValue >= 0 " is satisfied. 
*/	@org.junit.Test
	public void testApply39() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_targetValue = -1;
		exception.expect(Throwable.class);

		testObject.apply(mca_targetValue);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: targetValue <= 50 " is satisfied. 
*/	@org.junit.Test
	public void testApply40() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_targetValue = 51;
		exception.expect(Throwable.class);

		testObject.apply(mca_targetValue);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testApply41() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();

		testObject.apply(-118.14);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: targetValue >= 0 " is satisfied. 
*/	@org.junit.Test
	public void testApply42() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_targetValue = -1;
		exception.expect(Throwable.class);

		testObject.apply(mca_targetValue);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: targetValue <= 50 " is satisfied. 
*/	@org.junit.Test
	public void testApply43() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_targetValue = 51;
		exception.expect(Throwable.class);

		testObject.apply(mca_targetValue);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: targetValue >= 0 " is satisfied. 
*/	@org.junit.Test
	public void testApply44() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_targetValue = -1;
		exception.expect(Throwable.class);

		testObject.apply(mca_targetValue);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: targetValue <= 50 " is satisfied. 
*/	@org.junit.Test
	public void testApply45() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_targetValue = 51;
		exception.expect(Throwable.class);

		testObject.apply(mca_targetValue);
	};

/**
* Auto generated by random generation rule. 
*/	@org.junit.Test
	public void testApply46() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();

		testObject.apply(191.42);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: targetValue >= 0 " is satisfied. 
*/	@org.junit.Test
	public void testApply47() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_targetValue = -1;
		exception.expect(Throwable.class);

		testObject.apply(mca_targetValue);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: targetValue <= 50 " is satisfied. 
*/	@org.junit.Test
	public void testApply48() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_targetValue = 51;
		exception.expect(Throwable.class);

		testObject.apply(mca_targetValue);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: targetValue >= 0 " is satisfied. 
*/	@org.junit.Test
	public void testApply49() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_targetValue = -1;
		exception.expect(Throwable.class);

		testObject.apply(mca_targetValue);
	};

/**
* Auto generated by an OCL generation rule. Checks whether constraint "  pre: targetValue <= 50 " is satisfied. 
*/	@org.junit.Test
	public void testApply50() throws Throwable
	{
		SimulatedAnnealing testObject = new SimulatedAnnealing();
		double mca_targetValue = 51;
		exception.expect(Throwable.class);

		testObject.apply(mca_targetValue);
	};

};
